/** @jsxImportSource @emotion/react */
import { css } from '@emotion/react'
import Head from "next/head";
import Main from "../components/Main"

function Home(props) {

  const headingStyles = {zIndex:2, position:'relative'}
  const mainSectionStyles = {zIndex:2, position: 'relative'}

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main sprites={props.sprites || {}}>
        <h1 css={headingStyles}></h1>
        <section css={mainSectionStyles}>
        </section>
      </Main>

      <footer>asasda asda asd sdasd</footer>
    </>
  );
}

export async function getStaticProps() {
  try {
    let sprites = await fetch(`${process.env.NEXT_PUBLIC_HOST}/assets/character.json`)
    sprites = await sprites.json()
  
    const frames = {}

    sprites.frames.forEach(sprite => {
      const [animation, ...restPath] = sprite.filename.split('/')
      if(!frames[animation]) frames[animation] = []

      frames[animation].push({...sprite})
    });
  
    return {props: { sprites }}
  } catch(e) {
    console.error(e)
    return {props: { frames: {}}}
  }
} 

export default Home;